Repository pgRouting/pgrouting, pull requests merged in 2018-10, with the labels that each got.

#1108 Analyze graph doc
  doc/src/index.rst
  doc/src/pgRouting-concepts.rst
  doc/topology/pgr_analyzeGraph.rst
  doc/topology/pgr_analyzeOneWay.rst
  doc/topology/pgr_createTopology.rst
  doc/topology/pgr_createVerticesTable.rst
  doc/topology/pgr_nodeNetwork.rst
  doc/topology/topology-functions.rst
Labels: Documentation

#1109 [pgr_analyzeOneWay] Remove line under licence and fix errors
  doc/src/index.rst
  doc/src/pgRouting-concepts.rst
  doc/topology/pgr_analyzeGraph.rst
  doc/topology/pgr_analyzeOneWay.rst
  doc/topology/pgr_createTopology.rst
  doc/topology/pgr_createVerticesTable.rst
  doc/topology/pgr_nodeNetwork.rst
  doc/topology/topology-functions.rst
Labels: Documentation

#1110 Bddijkstra doc
  doc/bdDijkstra/bdDijkstra-family.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
  doc/src/routingFunctions.rst
Labels: Documentation

#1114 Documentation fixes
  doc/astar/pgr_aStar.rst
  doc/components/components-family.rst
  doc/components/pgr_articulationPoints.rst
  doc/src/index.rst
  doc/src/pgRouting-concepts.rst
  doc/src/proposed.rst
  doc/topology/pgr_createVerticesTable.rst
  doc/topology/topology-functions.rst
Labels: Documentation

#1105 bdDijkstra to official
  NEWS
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
  doc/src/proposed.rst
  doc/src/release_notes.rst
  doc/src/routingFunctions.rst
  sql/bdDijkstra/_bdDijkstra.sql
  sql/bdDijkstra/bdDijkstra.sql
  sql/bdDijkstra/bdDijkstraCost.sql
  sql/costMatrix/bdDijkstraCostMatrix.sql
Labels: bdDijkstra

#1115 Doc fixes
  doc/astar/pgr_aStarCost.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/bdAstar-family.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
Labels: Documentation

#1123 Doc function1
  tools/template/doc/pgr_function1.rst
Labels: Documentation

#1125 [documentation] Fixing several files
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/components/components-family.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/contraction/pgr_contractGraph.rst
  doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
  doc/dagShortestPath/pgr_dagShortestPath.rst
  doc/max_flow/pgr_boykovKolmogorov.rst
  doc/topology/pgr_createTopology.rst
  doc/topology/pgr_createVerticesTable.rst
Labels: Documentation

#1128 Official documentation
  doc/allpairs/pgr_johnson.rst
  doc/common/pgr_version.rst
  doc/ksp/pgr_KSP.rst
  doc/max_flow/pgr_maxCardinalityMatch.rst
  doc/max_flow/pgr_maxFlow.rst
  doc/max_flow/pgr_pushRelabel.rst
  doc/src/pgRouting-concepts.rst
  doc/topology/pgr_nodeNetwork.rst
  doc/trsp/pgr_trsp.rst
  doc/tsp/pgr_TSP.rst
Labels: Documentation

#1131 RandomSpanTree
  doc/mst/pgr_randomSpanTree.rst
Labels: Documentation

#1132 LineGraph-doc
  doc/lineGraph/pgr_lineGraph.rst
  doc/lineGraph/pgr_lineGraphFull.rst
Labels: Documentation

#1133 MinCostMaxFlow
  doc/costFlow/pgr_minCostMaxFlow.rst
  doc/costFlow/pgr_minCostMaxFlow_Cost.rst
  doc/src/pgRouting-concepts.rst
Labels: Documentation

#1134 directedChPP- doc
  doc/ChPP/pgr_directedChPP.rst
  doc/ChPP/pgr_directedChPP_Cost.rst
Labels: Documentation

#1135 [spanningTree-doc] Standarizing titles
  doc/mst/pgr_kruskal.rst
  doc/mst/pgr_prim.rst
Labels: Documentation

#1136 Doc Titles standarization
  doc/components/components-family.rst
  doc/components/pgr_strongComponents.rst
  doc/mincut/pgr_stoerWagner.rst
Labels: Documentation

#1139 Check first section
  doc/alpha_shape/pgr_alphaShape.rst
  doc/astar/pgr_aStar.rst
  doc/astar/pgr_aStarCost.rst
  doc/components/pgr_articulationPoints.rst
  doc/topology/pgr_analyzeGraph.rst
  doc/topology/pgr_analyzeOneWay.rst
Labels: Documentation

#1140 Doc- fixing first section
  doc/ChPP/pgr_directedChPP.rst
  doc/ChPP/pgr_directedChPP_Cost.rst
  doc/allpairs/pgr_floydWarshall.rst
  doc/allpairs/pgr_johnson.rst
  doc/alpha_shape/pgr_pointsAsPolygon.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/common/pgr_version.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/components/pgr_strongComponents.rst
  doc/costFlow/costFlow-family.rst
  doc/costFlow/pgr_minCostMaxFlow.rst
  doc/costFlow/pgr_minCostMaxFlow_Cost.rst
  doc/costMatrix/pgr_dijkstraCostMatrix.rst
  doc/costMatrix/pgr_withPointsCostMatrix.rst
  doc/dagShortestPath/pgr_dagShortestPath.rst
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraCost.rst
  doc/dijkstra/pgr_dijkstraVia.rst
  doc/ksp/pgr_KSP.rst
  doc/lineGraph/pgr_lineGraph.rst
  doc/lineGraph/pgr_lineGraphFull.rst
  doc/max_flow/flow-family.rst
  doc/max_flow/pgr_boykovKolmogorov.rst
  doc/max_flow/pgr_edgeDisjointPaths.rst
  doc/max_flow/pgr_edmondsKarp.rst
  doc/max_flow/pgr_maxCardinalityMatch.rst
  doc/max_flow/pgr_maxFlow.rst
  doc/max_flow/pgr_pushRelabel.rst
  doc/mincut/pgr_stoerWagner.rst
  doc/mst/pgr_kruskal.rst
  doc/mst/pgr_prim.rst
  doc/mst/pgr_randomSpanTree.rst
  doc/topology/pgr_createTopology.rst
  doc/topology/pgr_createVerticesTable.rst
  doc/topology/pgr_nodeNetwork.rst
  doc/trsp/pgr_trsp.rst
  doc/trsp/pgr_trspviaedges.rst
  doc/trsp/pgr_trspviavertices.rst
  doc/trsp/pgr_turnRestrictedPath.rst
  doc/tsp/pgr_TSP.rst
  doc/tsp/pgr_eucledianTSP.rst
  doc/vrp_basic/pgr_vrpOneDepot.rst
  doc/vrppdtw/pgr_gsoc_vrppdtw.rst
  doc/withPoints/pgr_withPoints.rst
  doc/withPoints/pgr_withPointsCost.rst
  doc/withPoints/pgr_withPointsDD.rst
  doc/withPoints/pgr_withPointsKSP.rst
Labels: Documentation

#1142 [WIP] fixing signatures on functions
  doc/astar/pgr_aStar.rst
  doc/astar/pgr_aStarCost.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
  doc/costMatrix/pgr_dijkstraCostMatrix.rst
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraCost.rst
  doc/driving_distance/pgr_drivingDistance.rst
  doc/ksp/pgr_KSP.rst
Labels: Documentation

#1144 Kruskal multivertex
  include/c_types/pgr_kruskal_t.h
  include/drivers/mst/kruskal_driver.h
  include/mst/pgr_kruskal.hpp
  pgtap/mst/kruskal-types-check.sql
  pgtap/mst/no_crash_test-kruskalBFS.sql
  pgtap/mst/no_crash_test-kruskalDD.sql
  pgtap/mst/no_crash_test-kruskalDFS.sql
  sql/mst/_kruskal.sql
  sql/mst/kruskal.sql
  sql/mst/kruskalBFS.sql
  sql/mst/kruskalDD.sql
  sql/mst/kruskalDFS.sql
  sql/sigs/pgrouting--3.0.0.sig
  src/mst/kruskal.c
  src/mst/kruskal_driver.cpp
  test/mst/doc-pgr_kruskalBFS.result
  test/mst/doc-pgr_kruskalBFS.test.sql
  test/mst/doc-pgr_kruskalDD.result
  test/mst/doc-pgr_kruskalDD.test.sql
  test/mst/doc-pgr_kruskalDFS.result
  test/mst/doc-pgr_kruskalDFS.test.sql
  test/mst/kruskal-flags.result
  test/mst/kruskal-flags.test.sql
Labels: kruskal

#1145 Fixing signatures
  doc/allpairs/pgr_floydWarshall.rst
  doc/allpairs/pgr_johnson.rst
  doc/astar/pgr_aStar.rst
  doc/astar/pgr_aStarCost.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraCost.rst
Labels: Documentation

#1147 Fixing signatures on documentation
  doc/allpairs/pgr_floydWarshall.rst
  doc/allpairs/pgr_johnson.rst
  doc/astar/pgr_aStarCost.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/components/pgr_articulationPoints.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/components/pgr_strongComponents.rst
  doc/costFlow/pgr_minCostMaxFlow.rst
  doc/costFlow/pgr_minCostMaxFlow_Cost.rst
  doc/dagShortestPath/pgr_dagShortestPath.rst
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraCost.rst
  doc/dijkstra/pgr_dijkstraVia.rst
  doc/ksp/pgr_KSP.rst
  doc/lineGraph/pgr_lineGraph.rst
  doc/lineGraph/pgr_lineGraphFull.rst
  doc/max_flow/pgr_boykovKolmogorov.rst
  doc/max_flow/pgr_edgeDisjointPaths.rst
  doc/max_flow/pgr_edmondsKarp.rst
  doc/max_flow/pgr_maxCardinalityMatch.rst
  doc/max_flow/pgr_maxFlow.rst
  doc/max_flow/pgr_pushRelabel.rst
  doc/mincut/pgr_stoerWagner.rst
  doc/mst/pgr_kruskal.rst
  doc/trsp/pgr_trsp.rst
  doc/withPoints/pgr_withPoints.rst
Labels: Documentation

#1149 doc-withPoints Fixed signatures and examples
  doc/costMatrix/pgr_withPointsCostMatrix.rst
  doc/mst/pgr_randomSpanTree.rst
  doc/withPoints/pgr_withPoints.rst
  doc/withPoints/pgr_withPointsCost.rst
  doc/withPoints/pgr_withPointsDD.rst
  doc/withPoints/pgr_withPointsKSP.rst
  doc/withPoints/pgr_withPointsVia.rst
Labels: Documentation
