Repository pgRouting/pgrouting, pull requests merged in 2018-09, with the labels that each got.

#1088 [bellmanFord][dag] Add STRICT to Sql files
  sql/bellman_ford/bellman_ford.sql
  sql/bellman_ford/bellman_ford_neg.sql
  sql/dagShortestPath/dagShortestPath.sql
Labels: Bug Fix

#1094 adding missing files & fixing some doc issues
  VERSION
  doc/ChPP/ChPP-family.rst
  doc/ChPP/pgr_directedChPP.rst
  doc/ChPP/pgr_directedChPP_Cost.rst
  doc/queries/CMakeLists.txt
  doc/queries/doc-kruskal.queries
  doc/queries/doc-pgr_dagShortestPath.queries
  doc/queries/doc-pgr_directedChPP.queries
  doc/queries/doc-pgr_directedChPP_Cost.queries
  doc/queries/doc-pgr_turnRestrictedPath.queries
  doc/queries/doc-prim.queries
  doc/queries/doc-stoerWagner.queries
  doc/src/proposed.rst
Labels: Bug Fix, Documentation

#1097 updating signature file for v3.0
  sql/sigs/pgrouting--3.0.0.sig
Labels: Administrative
