Repository pgRouting/pgrouting, pull requests merged in 2019-07, with the labels that each got.

#1224 New extract vertices
  NEWS
  doc/queries/doc-pgr_extractVertices.queries
  doc/src/proposed.rst
  doc/src/release_notes.rst
  doc/topology/pgr_extractVertices.rst
  pgtap/topology/extractVertices/edge-cases.sql
  pgtap/topology/extractVertices/no_crash_test.sql
  pgtap/topology/extractVertices/types-check.sql
  sql/sigs/pgrouting--3.0.0.sig
  sql/topology/extractVertices.sql
  test/topology/doc-pgr_extractVertices.result
  test/topology/doc-pgr_extractVertices.test.sql
Labels: Functionality/experimental, Topology

#1221 Documentation links
  doc/ChPP/pgr_directedChPP.rst
  doc/ChPP/pgr_directedChPP_Cost.rst
  doc/allpairs/pgr_floydWarshall.rst
  doc/allpairs/pgr_johnson.rst
  doc/alpha_shape/pgr_alphaShape.rst
  doc/astar/pgr_aStar.rst
  doc/astar/pgr_aStarCost.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/common/pgr_version.rst
  doc/components/pgr_articulationPoints.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/components/pgr_strongComponents.rst
  doc/contraction/pgr_contraction.rst
  doc/costFlow/pgr_minCostMaxFlow.rst
  doc/costFlow/pgr_minCostMaxFlow_Cost.rst
  doc/costMatrix/pgr_bdDijkstraCostMatrix.rst
  doc/costMatrix/pgr_dijkstraCostMatrix.rst
  doc/costMatrix/pgr_withPointsCostMatrix.rst
  doc/dijkstra/pgr_dijkstraCost.rst
Labels: Documentation, Enhancement

#1232 [sql][internal] using code in #529
  sql/common/CMakeLists.txt
  sql/common/_endPoint.sql
  sql/common/_startPoint.sql
  sql/common/pgrouting_utilities.sql
Labels: Enhancement
