Repository pgRouting/pgrouting, pull requests merged in 2019-06, with the labels that each got.

#1211 Create topology
  sql/topology/createtopology.sql
Labels: Enhancement

#1212 Official components
  NEWS
  doc/components/components-family.rst
  doc/components/pgr_articulationPoints.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/components/pgr_strongComponents.rst
  doc/src/proposed.rst
  doc/src/release_notes.rst
  doc/src/routingFunctions.rst
  sql/components/articulationPoints.sql
  sql/components/biconnectedComponents.sql
  sql/components/bridges.sql
  sql/components/connectedComponents.sql
  sql/components/strongComponents.sql
Labels: Administrative, G components

#1213 fix a wrong select apostrophe in doc
  doc/src/pgRouting-concepts.rst
Labels: Documentation

#1216 Create vertices table
  sql/topology/createverticestable.sql
Labels: Enhancement

#1217 Contraction proposed
  NEWS
  doc/contraction/CMakeLists.txt
  doc/contraction/contraction-family.rst
  doc/contraction/pgr_contractGraph.rst
  doc/contraction/pgr_contraction.rst
  doc/queries/CMakeLists.txt
  doc/queries/doc-contraction-family.queries
  doc/queries/doc-pgr_contraction.queries
  doc/src/proposed.rst
  doc/src/release_notes.rst
  pgtap/common/has_v3_signatures.sql
  pgtap/contraction/combined/dijkstra-compare.sql
  pgtap/contraction/contraction-types-check.sql
  pgtap/contraction/contraction_cycle_directed.sql
  pgtap/contraction/contraction_cycle_undirected.sql
  pgtap/contraction/deadend/directed/dijkstra-compare.sql
  pgtap/contraction/deadend/directed/directed-big-ids.sql
  pgtap/contraction/deadend/directed/directed-deadend-cases.sql
  pgtap/contraction/deadend/directed/directed-dev-deadend.sql
  pgtap/contraction/deadend/directed/directed-small_ids.sql
  pgtap/contraction/deadend/directed/directed-super-big-ids.sql
  pgtap/contraction/deadend/directed/directed_dead_end.sql
  pgtap/contraction/deadend/undirected/big-ids.sql
  pgtap/contraction/deadend/undirected/cases.sql
  pgtap/contraction/deadend/undirected/dev-cases.sql
  pgtap/contraction/deadend/undirected/dijkstra-compare.sql
  pgtap/contraction/deadend/undirected/more_cases.sql
  pgtap/contraction/deadend/undirected/small_ids.sql
  pgtap/contraction/deadend/undirected/super_big_ids.sql
  pgtap/contraction/issue1002/issue1002.sql
  pgtap/contraction/linear/directed/dijkstra-compare.sql
  pgtap/contraction/linear/directed/directed_linear.sql
  pgtap/contraction/linear/undirected/dijkstra-compare.sql
  pgtap/contraction/linear/undirected/undirected_linear.sql
  pgtap/contraction/no_crash_test-contraction.sql
  sql/contraction/contractGraph.sql
  sql/sigs/pgrouting--3.0.0.sig
  test/contraction/doc-contraction-family.result
  test/contraction/doc-contraction-family.test.sql
  test/contraction/doc-contraction.test.sql
  test/contraction/doc-pgr_contraction.result
  test/contraction/doc-pgr_contraction.test.sql
  test/contraction/test.conf
Labels: Administrative, Contraction

#1218 Node network
  sql/topology/nodeNetwork.sql
Labels: Enhancement

#1219 implicit cast for via_path integer to text
  sql/trsp/trsp_V2.2.sql
Labels: Enhancement

#1222 fix edge case for tsp when there is one or two nodes
  include/tsp/pgr_tsp.hpp
Labels: Bug Fix
