Repository pgRouting/pgrouting, pull requests merged in 2020-07, with the labels that each got.

#1368 pumping up to version 3.0.1
  .github/workflows/ubuntu.yml
  CMakeLists.txt
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  docqueries/version/doc-version.result
  sql/sigs/CMakeLists.txt
  sql/sigs/pgrouting--2.0.0.sig
  sql/sigs/pgrouting--2.0.1.sig
  sql/sigs/pgrouting--2.1.0.sig
  sql/sigs/pgrouting--2.2.0.sig
  sql/sigs/pgrouting--2.2.1.sig
  sql/sigs/pgrouting--2.2.2.sig
  sql/sigs/pgrouting--2.2.3.sig
  sql/sigs/pgrouting--2.2.4.sig
  sql/sigs/pgrouting--2.3.0.sig
  sql/sigs/pgrouting--2.3.1.sig
  sql/sigs/pgrouting--2.3.2.sig
  sql/sigs/pgrouting--2.4.0.sig
  sql/sigs/pgrouting--2.4.1.sig
  sql/sigs/pgrouting--2.4.2.sig
  sql/sigs/pgrouting--2.5.0.sig
  sql/sigs/pgrouting--2.5.2.sig
  sql/sigs/pgrouting--2.5.3.sig
  sql/sigs/pgrouting--2.5.4.sig
  sql/sigs/pgrouting--2.5.5.sig
  sql/sigs/pgrouting--3.0.1.sig
  sql/version/version.sql
  src/version/_version.h.in
  src/version/version.c
  tools/release-scripts/check-release.sh
  tools/testers/update-tester.sh
Labels: Administrative

#1369 Add code to interrupt the execution
  NEWS
  doc/src/pgRouting-introduction.rst
  doc/src/release_notes.rst
  include/allpairs/pgr_allpairs.hpp
  include/astar/pgr_astar.hpp
  include/bellman_ford/pgr_bellman_ford.hpp
  include/bellman_ford/pgr_edwardMoore.hpp
  include/breadthFirstSearch/pgr_breadthFirstSearch.hpp
  include/contraction/pgr_deadEndContraction.hpp
  include/cpp_common/interruption.h
  include/dagShortestPath/pgr_dagShortestPath.hpp
  include/dijkstra/pgr_dijkstra.hpp
  include/max_flow/pgr_maxflow.hpp
  include/spanningTree/pgr_kruskal.hpp
  include/spanningTree/pgr_mst.hpp
  include/spanningTree/pgr_prim.hpp
  include/spanningTree/pgr_randomSpanningTree.hpp
  include/topologicalSort/pgr_topologicalSort.hpp
  locale/en/LC_MESSAGES/index.po
  locale/en/LC_MESSAGES/pgRouting-introduction.po
  locale/en/LC_MESSAGES/release_notes.po
  locale/pot/index.pot
  locale/pot/pgRouting-introduction.pot
  locale/pot/release_notes.pot
  src/alpha_shape/pgr_alphaShape.cpp
  src/components/pgr_components.cpp
  src/trsp/trsp.c
Labels: Enhancement

#1370 test database name fixed
  tools/developer/taptest.sh
Labels: Bug Fix

#1376 Lint 3.1
  CMakeLists.txt
  NEWS
  ci/debbie/regress.sh
  ci/travis/doc-quieries_test.sh
  docqueries/version/doc-full_version.result
  include/c_types/pgr_edge_t.h
  include/chinese/pgr_chinesePostman.hpp
  include/dijkstra/pgr_dijkstra.hpp
  include/transitiveClosure/pgr_transitiveClosure.hpp
  src/breadthFirstSearch/breadthFirstSearch_driver.cpp
  src/common/basePath_SSEC.cpp
  src/common/basic_vertex.cpp
  src/common/xy_vertex.cpp
  src/pickDeliver/node.cpp
  tools/developer/run.sh
  tools/developer/taptest.sh
  tools/developer/translate.sh
  tools/release-scripts/check-release.sh
  tools/release-scripts/compile-release.sh
  tools/testers/pg_prove_tests.sh
  tools/testers/update-tester.sh
  tools/transifex/download_translation.sh
  tools/winnie/build_pgrouting.sh
  tools/winnie/package_pgrouting.sh
Labels: Build, C/C++

#1377 [build] fixes for visual studio
  CMakeLists.txt
  docqueries/version/doc-full_version.result
  include/cpp_common/interruption.h
  include/dagShortestPath/pgr_dagShortestPath.hpp
  include/dijkstra/pgr_dijkstra.hpp
  src/common/basePath_SSEC.cpp
  src/dijkstra/dijkstra_driver.cpp
Labels: Build, C/C++

#1391 [travis] skiping code check
  .travis.yml
Labels: Build

#1395 dont test code on PR of only translations
  .travis.yml
Labels: Build

#1414 [travis] Do nothing on travis when translations
  .github/workflows/linkcheck-es.yml
  .travis.yml
Labels: Build

#1494 [pumpup] Pumping up develop to 3.2.0
  CMakeLists.txt
  NEWS
  doc/src/pgRouting-introduction.rst
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  docqueries/version/doc-version.result
  sql/scripts/build-extension-update-files1.pl
  sql/sigs/CMakeLists.txt
  sql/sigs/pgrouting--3.2.0.sig
  tools/developer/pumpup-dev.sh
Labels: Administrative

#1500 not testing macos action
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: Administrative

#1499 [linkcheck] adding some configuration to link checking
  doc/conf.py.in
Labels: Administrative

#1502 not testing macos action
  .github/workflows/macos.yml
  .github/workflows/windows.yml
Labels: Administrative

#1531 [actions] test for signature files not changing on same minor
  .github/workflows/check-files.yml
Labels: Administrative

#1533 [actions] test for signature files not changing on same minor (#1531)
  .github/workflows/check-files.yml
  .github/workflows/linkcheck-es.yml
Labels: Administrative
