Repository pgRouting/pgrouting, pull requests merged in 2020-11, with the labels that each got.

#1650 Fixing description of cost matrix
  doc/src/pgRouting-concepts.rst
Labels: Documentation

#1641 fix issue 1640 pgr_withPoints
  pgtap/withPoints/issue1640.sql
  pgtap/withPoints/withPoints_oneToOne-compare-dijkstra.test.sql
  src/withPoints/withPoints_driver.cpp
Labels: Bug Fix, withPoints

#1651 Porting 1650
  doc/src/pgRouting-concepts.rst
  locale/en/LC_MESSAGES/pgRouting-concepts.po
  locale/pot/pgRouting-concepts.pot
Labels: Documentation

#1719 Issue 1647 3.0
  NEWS
  doc/src/release_notes.rst
  include/contraction/pgr_contractionGraph.hpp
  pgtap/contraction/linear/directed/issue-1647.sql
  pgtap/contraction/linear/undirected/issue-1647.sql
Labels: Bug Fix

#1720 Issue 1647 3.1
  NEWS
  doc/src/release_notes.rst
  include/contraction/pgr_contractionGraph.hpp
  pgtap/contraction/linear/directed/issue-1647.sql
  pgtap/contraction/linear/undirected/issue-1647.sql
Labels: Bug Fix

#1721 Issue 1647 dev
  NEWS
  doc/src/release_notes.rst
  include/contraction/pgr_contractionGraph.hpp
  locale/en/LC_MESSAGES/release_notes.po
  locale/pot/release_notes.pot
  pgtap/contraction/linear/directed/issue-1647.sql
  pgtap/contraction/linear/undirected/issue-1647.sql
Labels: Bug Fix

#1724 [chinese] fixing server crash for 3.1
  include/chinese/pgr_chinesePostman.hpp
  include/max_flow/pgr_minCostMaxFlow.hpp
Labels: Bug Fix

#1723 [chinese] fixing server crash on 3.0
  include/chinese/pgr_chinesePostman.hpp
  include/max_flow/pgr_minCostMaxFlow.hpp
Labels: Bug Fix

#1722 [chinese] fixing server crash on develop
  include/chinese/pgr_chinesePostman.hpp
  include/max_flow/pgr_minCostMaxFlow.hpp
Labels: Bug Fix, ChPP

#1728 checking & fixing licenses
  .github/workflows/check-files.yml
  doc/CNAME
  doc/_templates/layout.html
  doc/conf.py.in
  doc/dagShortestPath/doc-pgr_dagShortestPath.queries
  doc/make.bat
  doc/mincut/CMakeLists.txt
  doc/mincut/doc-pgr_stoerWagner.queries
  doc/mincut/pgr_stoerWagner.rst
  sql/scripts/build-extension-file.pl
  sql/scripts/build-extension-update-files1.pl
  tools/scripts/README.txt
  tools/scripts/test_license.sh
Labels: CI

#1727 checking & fixing licenses
  .github/workflows/check-files.yml
  doc/CNAME
  doc/_templates/layout.html
  doc/conf.py.in
  doc/dagShortestPath/doc-pgr_dagShortestPath.queries
  doc/make.bat
  doc/mincut/CMakeLists.txt
  doc/mincut/doc-pgr_stoerWagner.queries
  doc/mincut/pgr_stoerWagner.rst
  sql/scripts/build-extension-file.pl
  sql/scripts/build-extension-update-files1.pl
  tools/scripts/README.txt
  tools/scripts/test_license.sh
Labels: CI

#1726 checking & fixing licenses
  .github/workflows/check-files.yml
  doc/CNAME
  doc/_templates/layout.html
  doc/conf.py.in
  doc/dagShortestPath/doc-pgr_dagShortestPath.queries
  doc/make.bat
  doc/mincut/CMakeLists.txt
  doc/mincut/doc-pgr_stoerWagner.queries
  doc/mincut/pgr_stoerWagner.rst
  sql/scripts/build-extension-file.pl
  sql/scripts/build-extension-update-files1.pl
  tools/scripts/README.txt
  tools/scripts/test_license.sh
Labels: CI

#1729 [CI] testing and fixing shell code
  .github/workflows/check-files.yml
  .github/workflows/check-queries.yml
  ci/bessie/regress.sh
  ci/bessie32/regress.sh
  ci/debbie/regress.sh
  ci/travis/doc-quieries_test.sh
  tools/developer/run.sh
  tools/release-scripts/check-release.sh
  tools/release-scripts/get_signatures.sh
  tools/scripts/code_checker.sh
  tools/scripts/fix_typos.sh
  tools/scripts/test_license.sh
  tools/scripts/test_shell.sh
  tools/testers/update-tester.sh
  tools/transifex/build_translations.sh
  tools/transifex/create_translations.sh
  tools/winnie/build_pgrouting.sh
  tools/winnie/package_pgrouting.sh
Labels: CI

#1730 [CI] testing and fixing shell code
  .github/workflows/check-files.yml
  .github/workflows/check-queries.yml
  ci/bessie/regress.sh
  ci/bessie32/regress.sh
  ci/debbie/regress.sh
  ci/travis/doc-quieries_test.sh
  tools/developer/run.sh
  tools/release-scripts/check-release.sh
  tools/release-scripts/get_signatures.sh
  tools/scripts/code_checker.sh
  tools/scripts/fix_typos.sh
  tools/scripts/test_license.sh
  tools/scripts/test_shell.sh
  tools/testers/update-tester.sh
  tools/transifex/build_translations.sh
  tools/transifex/create_translations.sh
  tools/winnie/build_pgrouting.sh
  tools/winnie/package_pgrouting.sh
Labels: CI

#1731 [CI] testing and fixing shell code
  .github/workflows/check-files.yml
  .github/workflows/check-queries.yml
  ci/bessie/regress.sh
  ci/bessie32/regress.sh
  ci/debbie/regress.sh
  ci/travis/doc-quieries_test.sh
  docqueries/version/doc-full_version.result
  tools/developer/run.sh
  tools/release-scripts/check-release.sh
  tools/release-scripts/get_signatures.sh
  tools/scripts/code_checker.sh
  tools/scripts/fix_typos.sh
  tools/scripts/test_license.sh
  tools/scripts/test_shell.sh
  tools/testers/update-tester.sh
  tools/transifex/build_translations.sh
  tools/transifex/create_translations.sh
  tools/winnie/build_pgrouting.sh
  tools/winnie/package_pgrouting.sh
Labels: CI

#1742 Fix issue 1640 pgr_withPoints (#1641)
  pgtap/withPoints/issue1640.sql
  pgtap/withPoints/withPoints_oneToOne-compare-dijkstra.test.sql
  src/withPoints/withPoints_driver.cpp
Labels: Bug Fix, withPoints

#1741 Fix issue 1640 pgr_withPoints (#1641)
  pgtap/withPoints/issue1640.sql
  pgtap/withPoints/withPoints_oneToOne-compare-dijkstra.test.sql
  src/withPoints/withPoints_driver.cpp
Labels: Bug Fix, withPoints

#1761 [build] pump up to version 3.0.4
  CMakeLists.txt
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  docqueries/version/doc-version.result
Labels: Administrative

#1763 [build] fixing 1356 on 3.0
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  tools/testers/pg_prove_tests.sh
Labels: Bug Fix, Build

#1764 [build] fixing #1356 on 3.1
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  tools/testers/pg_prove_tests.sh
Labels: Bug Fix, Build
