Repository pgRouting/pgrouting, pull requests merged in 2020-10, with the labels that each got.

#1620 Modified release_notes.rst and NEWS
  NEWS
  doc/src/release_notes.rst
Labels: Documentation

#1622 Removing codeforce link
  doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
  locale/en/LC_MESSAGES/pgr_binaryBreadthFirstSearch.po
  locale/pot/pgr_binaryBreadthFirstSearch.pot
Labels: Documentation, Enhancement

#1619 Issue 1616 for 3 0
  CMakeLists.txt
  NEWS
  doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  docqueries/version/doc-version.result
  docqueries/withPoints/doc-pgr_withPointsKSP.result
  include/yen/pgr_ksp.hpp
  sql/sigs/CMakeLists.txt
  sql/sigs/pgrouting--3.0.3.sig
  src/bellman_ford/bellman_ford_driver.cpp
  src/dijkstra/dijkstra_driver.cpp
  tools/release-scripts/check-release.sh
  tools/testers/update-tester.sh
Labels: Bug Fix

#1643 Fix Issue 1300 on 3.2
  NEWS
  doc/src/release_notes.rst
  docqueries/chinese/doc-pgr_chinesePostman.result
  include/chinese/pgr_chinesePostman.hpp
  pgtap/chinese/chinesePostman/innerQuery.sql
  pgtap/contraction/deadend/directed/directed_dead_end.sql
  sql/chinese/_pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostmanCost.sql
  src/chinese/chinesePostman.c
  src/chinese/chinesePostman_driver.cpp
Labels: Bug Fix, ChPP

#1642 fix issue 1300 on 3.0
  NEWS
  doc/src/release_notes.rst
  docqueries/chinese/doc-pgr_chinesePostman.result
  include/chinese/pgr_chinesePostman.hpp
  pgtap/chinese/chinesePostman/innerQuery.sql
  pgtap/contraction/deadend/directed/directed_dead_end.sql
  sql/chinese/_pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostmanCost.sql
  src/chinese/chinesePostman.c
  src/chinese/chinesePostman_driver.cpp
Labels: Bug Fix, ChPP

#1638 fix issue 1300 on 3.1
  NEWS
  doc/src/release_notes.rst
  docqueries/chinese/doc-pgr_chinesePostman.result
  include/chinese/pgr_chinesePostman.hpp
  pgtap/chinese/chinesePostman/innerQuery.sql
  pgtap/contraction/deadend/directed/directed_dead_end.sql
  sql/chinese/_pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostman.sql
  sql/chinese/pgr_chinesePostmanCost.sql
  src/chinese/chinesePostman.c
  src/chinese/chinesePostman_driver.cpp
Labels: Bug Fix, ChPP

#1644 Fixing issue 1616 on withPoints
  src/withPoints/withPoints_driver.cpp
Labels: Enhancement, withPoints

#1645 Fixing issue 1616 on withPoints
  src/withPoints/withPoints_driver.cpp
Labels: Enhancement, withPoints

#1646 Fixing issue 1616 on withPoints
  src/withPoints/withPoints_driver.cpp
Labels: Enhancement, withPoints
