Repository pgRouting/pgrouting, pull requests merged in 2021-07, with the labels that each got.

#1971 [actions] celaning up actions
  .github/workflows/boost_version.yml
  .github/workflows/check-files.yml
  .github/workflows/check-queries.yml
  .github/workflows/clang.yml
  .github/workflows/doc-check.yml
  .github/workflows/documentation.yml
  .github/workflows/macos.yml
  .github/workflows/publish-users-doc.yml
  .github/workflows/ubuntu.yml
  .github/workflows/update.yml
Labels: Administrative

#1979 [breadthFirstSearch] removing directive PGSQL_VERSION > 95
  src/breadthFirstSearch/binaryBreadthFirstSearch.c
  src/breadthFirstSearch/breadthFirstSearch.c
Labels: OSD

#1975 [astar] removing directive PGSQL_VERSION > 95
  src/astar/astar.c
Labels: OSD

#1976 [bdAstar] removing directive PGSQL_VERSION > 95
  src/bdAstar/bdAstar.c
Labels: OSD

#1977 [max_flow] removing directive PGSQL_VERSION > 95
  src/max_flow/edge_disjoint_paths.c
  src/max_flow/max_flow.c
  src/max_flow/maximum_cardinality_matching.c
  src/max_flow/minCostMaxFlow.c
Labels: OSD

#1978 [bellman_ford] removing directive PGSQL_VERSION > 95
  src/bellman_ford/bellman_ford.c
  src/bellman_ford/bellman_ford_neg.c
  src/bellman_ford/edwardMoore.c
Labels: OSD

#1980 [dijkstra] removing directive PGSQL_VERSION > 95
  src/dijkstra/dijkstra.c
  src/dijkstra/dijkstraVia.c
Labels: OSD

#1983 [spanningTree] removing directive PGSQL_VERSION > 95
  src/spanningTree/kruskal.c
  src/spanningTree/prim.c
  src/spanningTree/randomSpanningTree.c
Labels: OSD

#1985 [topologicalSort] removing directive PGSQL_VERSION > 95
  src/topologicalSort/topologicalSort.c
Labels: OSD

#1986 [bdDijkstra] removing directive PGSQL_VERSION > 95
  src/bdDijkstra/bdDijkstra.c
Labels: OSD

#1987 [chinese] removing directive PGSQL_VERSION > 95
  src/chinese/chinesePostman.c
Labels: OSD

#1988 [tsp] removing directive PGSQL_DIRECTIVE > 95
  src/tsp/TSP.c
  src/tsp/euclideanTSP.c
Labels: OSD

#1989 fix for Issue1896 Coordinate_t
  include/c_common/coordinates_input.h
  include/c_types/coordinate_t.h
  src/common/coordinates_input.c
Labels: OSD

#1990 [traversal] removing directive PGSQL_VERSION > 95
  src/traversal/depthFirstSearch.c
Labels: OSD

#1993 [src/dagShortestPath] removing directive PGSQL_VERSION > 95
  src/dagShortestPath/dagShortestPath.c
Labels: OSD

#1992 fix for Issue1897 Delauny_t
  include/c_common/delauny_input.h
  include/c_types/delauny_t.h
Labels: OSD

#1996 fix for Issue1921 pgr_vertex_color_rt
  include/c_types/pgr_vertex_color_rt.h
  include/coloring/pgr_sequentialVertexColoring.hpp
  include/drivers/coloring/sequentialVertexColoring_driver.h
  src/coloring/sequentialVertexColoring.c
Labels: OSD

#1997 [src/trsp] removing directive PGSQL_VERSION > 95
  src/trsp/trsp.c
Labels: OSD

#1999 [src/coloring] removing directive PGSQL_VERSION > 95
  src/coloring/bipartite.c
  src/coloring/sequentialVertexColoring.c
Labels: OSD

#1998 [src/mincut] removing directive PGSQL_VERSION > 94
  src/mincut/stoerWagner.c
Labels: OSD

#2000 [src/withPoints] removing directive PGSQL_VERSION > 95
  src/withPoints/withPoints.c
Labels: OSD

#2002 [src/contraction] removing directive PGSQL_VERSION > 95
  src/contraction/contractGraph.c
Labels: OSD

#2003 [src/dominator] removing directive PGSQL_VERSION > 95
  src/dominator/lengauerTarjanDominatorTree.c
Labels: OSD

#2005 [src/pickDeliver] removing directive PGSQL_VERSION > 95
  src/pickDeliver/pickDeliver.c
  src/pickDeliver/pickDeliverEuclidean.c
Labels: OSD

#2007 fix for Issue1898 General_path_element_t
  include/c_types/general_path_element_t.h
  include/drivers/astar/astar_driver.h
  include/drivers/bdDijkstra/bdDijkstra_driver.h
  include/drivers/bellman_ford/bellman_ford_driver.h
  include/drivers/bellman_ford/edwardMoore_driver.h
  include/drivers/breadthFirstSearch/binaryBreadthFirstSearch_driver.h
  include/drivers/chinese/chinesePostman_driver.h
  include/drivers/dagShortestPath/dagShortestPath_driver.h
  include/drivers/dijkstra/dijkstra_driver.h
  include/drivers/driving_distance/drivedist_driver.h
  include/drivers/driving_distance/withPoints_dd_driver.h
  include/drivers/max_flow/edge_disjoint_paths_driver.h
  include/drivers/trsp/trsp_driver.h
  include/drivers/tsp/TSP_driver.h
  include/drivers/tsp/euclideanTSP_driver.h
  include/drivers/withPoints/withPoints_driver.h
  include/drivers/yen/ksp_driver.h
  include/drivers/yen/turnRestrictedPath_driver.h
  include/drivers/yen/withPoints_ksp_driver.h
  src/astar/astar.c
  src/bdDijkstra/bdDijkstra.c
  src/bellman_ford/bellman_ford.c
  src/bellman_ford/edwardMoore.c
  src/breadthFirstSearch/binaryBreadthFirstSearch.c
  src/chinese/chinesePostman.c
  src/dagShortestPath/dagShortestPath.c
  src/dijkstra/dijkstra.c
  src/driving_distance/many_to_dist_driving_distance.c
  src/driving_distance/many_to_dist_withPointsDD.c
  src/ksp/ksp.c
  src/ksp/turnRestrictedPath.c
  src/ksp/withPoints_ksp.c
  src/max_flow/edge_disjoint_paths.c
  src/tsp/TSP.c
  src/tsp/TSP_driver.cpp
  src/tsp/euclideanTSP.c
  src/tsp/euclideanTSP_driver.cpp
  src/withPoints/withPoints.c
Labels: OSD

#2004 [src/driving_distance] removing directive PGSQL_VERSION > 95
  src/driving_distance/many_to_dist_driving_distance.c
  src/driving_distance/many_to_dist_withPointsDD.c
Labels: OSD

#2008 [src/transitiveClosure] removing directive PGSQL_VERSION > 95
  src/transitiveClosure/transitiveClosure.c
Labels: OSD

#1931 fix for Issue1903 Matrix_cell_t
  include/allpairs/pgr_allpairs.hpp
  include/c_common/matrixRows_input.h
  include/c_types/matrix_cell_t.h
  include/cpp_common/Dmatrix.h
  include/drivers/allpairs/floydWarshall_driver.h
  include/drivers/allpairs/johnson_driver.h
  src/allpairs/floydWarshall.c
  src/allpairs/johnson.c
  src/common/matrixRows_input.c
  src/cpp_common/Dmatrix.cpp
Labels: OSD

#1967 [allpairs] removing directive PGSQL_VERSION > 95
  src/allpairs/floydWarshall.c
  src/allpairs/johnson.c
Labels: OSD

#2009 fix for 1912 adjustments for pgr_flow_t
  include/c_common/edges_input.h
  include/c_types/pgr_flow_t.h
  include/drivers/max_flow/max_flow_driver.h
  include/drivers/max_flow/minCostMaxFlow_driver.h
  src/common/edges_input.c
  src/max_flow/max_flow.c
  src/max_flow/minCostMaxFlow.c
Labels: OSD

#2012 fix for Issue1901 Line_graph_full_rt
  include/c_types/line_graph_full_rt.h
  include/drivers/lineGraph/lineGraphFull_driver.h
  src/lineGraph/lineGraphFull.c
  src/lineGraph/lineGraphFull_driver.cpp
Labels: OSD

#2013 fix for Issue1902 Line_graph_rt
  include/c_types/line_graph_rt.h
  include/drivers/lineGraph/lineGraph_driver.h
  src/lineGraph/lineGraph.c
  src/lineGraph/lineGraph_driver.cpp
Labels: OSD

#2017 fix for Issue1904 pgr_basic_edge_t
  include/c_common/edges_input.h
  include/c_types/pgr_basic_edge_t.h
  src/common/edges_input.c
Labels: OSD

#2021 fix for issue1906 pgr_boyer_t
  include/c_types/pgr_boyer_t.h
Labels: OSD

#2022 fix for Issue1909 pgr_costFlow_t
  include/c_common/edges_input.h
  include/c_types/pgr_costFlow_t.h
  src/common/edges_input.c
Labels: OSD

#2023 Fix stylecheck
  include/topologicalSort/pgr_topologicalSort.hpp
  src/chinese/chinesePostman.c
  src/components/strongComponents.c
  src/driving_distance/many_to_dist_withPointsDD.c
  src/topologicalSort/topologicalSort_driver.cpp
  tools/scripts/code_checker.sh
Labels: CI

#2032 fixed issue1916 Pgr_point_t
  include/c_common/pgr_point_input.h
  include/c_types/pgr_point_t.h
  src/common/pgr_point_input.c
Labels: OSD
