Repository pgRouting/pgrouting, pull requests merged in 2021-01, with the labels that each got.

#1841 Support macOS on CI (#1840)
  .github/workflows/macos.yml
Labels: CI, MacOS

#1842 Support macOS on CI (#1840)
  .github/workflows/macos.yml
Labels: CI, MacOS

#1852 Changed license to GPL-2.0+ on 3.2
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Documentation

#1853 Change license to GPL-2.0+ on 3.1
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Documentation

#1854 Change license to GPL-2.0+ on 3.0
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Documentation

#1860 Change license to GPL-2.0-or-later on 3.0
  CONTRIBUTING.md
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Administrative

#1859 Change license to GPL-2.0-or-later on 3.2
  CONTRIBUTING.md
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Administrative

#1858 Change license to GPL-2.0-or-later on 3.1
  CONTRIBUTING.md
  README.md
  doc/src/pgRouting-introduction.rst
Labels: Administrative

#1864 [pickDeliver] Removing singleton
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  include/cpp_common/pgr_messages.h
  include/vrp/dnode.h
  include/vrp/fleet.h
  include/vrp/optimize.h
  include/vrp/pd_orders.h
  include/vrp/pd_problem.h
  include/vrp/pgr_pickDeliver.h
  include/vrp/solution.h
  include/vrp/vehicle.h
  src/cpp_common/pgr_messages.cpp
  src/pickDeliver/CMakeLists.txt
  src/pickDeliver/dnode.cpp
  src/pickDeliver/fleet.cpp
  src/pickDeliver/initial_solution.cpp
  src/pickDeliver/optimize.cpp
  src/pickDeliver/pd_orders.cpp
  src/pickDeliver/pd_problem.cpp
  src/pickDeliver/pgr_pickDeliver.cpp
  src/pickDeliver/solution.cpp
  src/pickDeliver/vehicle.cpp
Labels: Bug Fix, Pick & Delivery, VRP-OneDepot

#1863 [pickDeliver] Removing singleton
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  include/cpp_common/pgr_messages.h
  include/vrp/dnode.h
  include/vrp/fleet.h
  include/vrp/optimize.h
  include/vrp/pd_orders.h
  include/vrp/pd_problem.h
  include/vrp/pgr_pickDeliver.h
  include/vrp/solution.h
  include/vrp/vehicle.h
  src/cpp_common/pgr_messages.cpp
  src/pickDeliver/CMakeLists.txt
  src/pickDeliver/dnode.cpp
  src/pickDeliver/fleet.cpp
  src/pickDeliver/initial_solution.cpp
  src/pickDeliver/optimize.cpp
  src/pickDeliver/pd_orders.cpp
  src/pickDeliver/pd_problem.cpp
  src/pickDeliver/pgr_pickDeliver.cpp
  src/pickDeliver/pickDeliverEuclidean.c
  src/pickDeliver/pickDeliver_driver.cpp
  src/pickDeliver/solution.cpp
  src/pickDeliver/vehicle.cpp
Labels: Bug Fix, Pick & Delivery, VRP-OneDepot

#1862 [pickDeliver] Removing singleton
  NEWS
  doc/src/release_notes.rst
  docqueries/version/doc-full_version.result
  include/cpp_common/pgr_messages.h
  include/vrp/dnode.h
  include/vrp/fleet.h
  include/vrp/optimize.h
  include/vrp/pd_orders.h
  include/vrp/pd_problem.h
  include/vrp/pgr_pickDeliver.h
  include/vrp/solution.h
  include/vrp/vehicle.h
  src/cpp_common/pgr_messages.cpp
  src/pickDeliver/CMakeLists.txt
  src/pickDeliver/dnode.cpp
  src/pickDeliver/fleet.cpp
  src/pickDeliver/initial_solution.cpp
  src/pickDeliver/optimize.cpp
  src/pickDeliver/pd_orders.cpp
  src/pickDeliver/pd_problem.cpp
  src/pickDeliver/pgr_pickDeliver.cpp
  src/pickDeliver/pickDeliverEuclidean.c
  src/pickDeliver/pickDeliver_driver.cpp
  src/pickDeliver/solution.cpp
  src/pickDeliver/vehicle.cpp
Labels: Bug Fix, Pick & Delivery, VRP-OneDepot

#1855 Add GitHub Actions script for releases on 3.2
  .github/workflows/release.yml
  NEWS
  doc/src/release_notes.rst
  tools/release-scripts/notes2news.pl
Labels: CI

#1856 Add GitHub Actions script for releases on 3.0
  .github/workflows/release.yml
  NEWS
  doc/src/release_notes.rst
  tools/release-scripts/notes2news.pl
Labels: CI

#1857 Add GitHub Actions script for releases on 3.1
  .github/workflows/release.yml
  NEWS
  doc/src/release_notes.rst
  tools/release-scripts/notes2news.pl
Labels: CI
