Repository pgRouting/pgrouting, pull requests merged in 2022-09, with the labels that each got.

#2364 [GSoC-2022] Experimental Function - cuthillMckeeOrdering
  configuration.conf
  doc/conf.py.in
  doc/ordering/CMakeLists.txt
  doc/ordering/cuthillMckeeOrdering.rst
  doc/ordering/ordering-family.rst
  doc/src/experimental.rst
  doc/src/pgRouting-introduction.rst
  docqueries/ordering/CMakeLists.txt
  docqueries/ordering/cuthillMckeeOrdering.result
  docqueries/ordering/cuthillMckeeOrdering.test.sql
  docqueries/ordering/test.conf
  include/drivers/ordering/cuthillMckeeOrdering_driver.h
  include/ordering/cuthillMckeeOrdering.hpp
  pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
  pgtap/ordering/cuthillMckeeOrdering/inner_query.pg
  pgtap/ordering/cuthillMckeeOrdering/no_crash_test.pg
  pgtap/ordering/cuthillMckeeOrdering/types_check.pg
  sql/ordering/CMakeLists.txt
  sql/ordering/_cuthillMckeeOrdering.sql
  sql/ordering/cuthillMckeeOrdering.sql
  sql/sigs/pgrouting--3.4.sig
  src/ordering/CMakeLists.txt
  src/ordering/cuthillMckeeOrdering.c
  src/ordering/cuthillMckeeOrdering_driver.cpp
Labels: Functionality/New, Functionality/experimental, GSoC-2022

#2370 Release tasks 1
  .github/workflows/ubuntu.yml
  .github/workflows/update.yml
  CMakeLists.txt
  doc/_static/custom.css
  doc/allpairs/pgr_floydWarshall.rst
  doc/allpairs/pgr_johnson.rst
  doc/alpha_shape/pgr_alphaShape.rst
  doc/astar/pgr_aStar.rst
  doc/astar/pgr_aStarCost.rst
  doc/astar/pgr_aStarCostMatrix.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdAstar/pgr_bdAstarCost.rst
  doc/bdAstar/pgr_bdAstarCostMatrix.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bdDijkstra/pgr_bdDijkstraCost.rst
  doc/bdDijkstra/pgr_bdDijkstraCostMatrix.rst
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/bellman_ford/pgr_edwardMoore.rst
  doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
  doc/breadthFirstSearch/pgr_breadthFirstSearch.rst
  doc/chinese/pgr_chinesePostman.rst
  doc/chinese/pgr_chinesePostmanCost.rst
  doc/circuits/CMakeLists.txt
  doc/circuits/pgr_hawickCircuits.rst
  doc/conf.py.in
  doc/src/experimental.rst
  doc/traversal/BFS-category.rst
  docqueries/src/migration.result
  docqueries/trsp/four_edges.result
  docqueries/trsp/issue693.result
  docqueries/trsp/issue704.result
  docqueries/trsp/issue717.result
  docqueries/trsp/trsp-any-02.result
  docqueries/trsp/trsp-renumber.result
  docqueries/trsp/trsp_vias-any-04.result
  docqueries/version/doc-full_version.result
  docqueries/version/doc-version.result
  pgtap/ordering/cuthillMckeeOrdering/edge_cases.pg
  pgtap/trsp/trsp/edge_cases/issue_244.pg
  pgtap/trsp/trspVia/compare_dijkstraVia/no_restrictions_directed.pg
  pgtap/trsp/trspVia/compare_dijkstraVia/no_restrictions_undirected.pg
  pgtap/trsp/trspVia_withPoints/compare_dijkstraVia/no_restrictions_directed.pg
  pgtap/trsp/trspVia_withPoints/compare_dijkstraVia/no_restrictions_undirected.pg
  pgtap/withPoints/withPointsVia/compare_dijkstraVia/directed.pg
  pgtap/withPoints/withPointsVia/compare_dijkstraVia/undirected.pg
  sql/circuits/hawickCircuits.sql
  sql/max_flow/maxCardinalityMatch.sql
  sql/trsp/pgr_trsp.sql
  sql/trsp/pgr_trspViaEdges.sql
  sql/trsp/pgr_trspViaVertices.sql
  sql/withPoints/withPointsVia.sql
  tools/developer/taptest.sh
  tools/testers/types_check.sql
  tools/testers/via_compare.sql
Labels: Administrative

#2372 Release tasks 2
  doc/coloring/pgr_bipartite.rst
  doc/coloring/pgr_edgeColoring.rst
  doc/coloring/pgr_sequentialVertexColoring.rst
  doc/components/pgr_articulationPoints.rst
  doc/components/pgr_biconnectedComponents.rst
  doc/components/pgr_bridges.rst
  doc/components/pgr_connectedComponents.rst
  doc/components/pgr_makeConnected.rst
  doc/components/pgr_strongComponents.rst
  doc/conf.py.in
  doc/contraction/pgr_contraction.rst
  doc/dagShortestPath/pgr_dagShortestPath.rst
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraCost.rst
  doc/dijkstra/pgr_dijkstraCostMatrix.rst
  doc/dijkstra/pgr_dijkstraNear.rst
  doc/dijkstra/pgr_dijkstraNearCost.rst
  doc/dijkstra/pgr_dijkstraVia.rst
  doc/dominator/pgr_lengauerTarjanDominatorTree.rst
  doc/driving_distance/pgr_drivingDistance.rst
  doc/ksp/pgr_KSP.rst
  doc/lineGraph/pgr_lineGraph.rst
  doc/lineGraph/pgr_lineGraphFull.rst
  doc/max_flow/pgr_boykovKolmogorov.rst
  doc/max_flow/pgr_edgeDisjointPaths.rst
  doc/max_flow/pgr_maxCardinalityMatch.rst
  doc/max_flow/pgr_maxFlow.rst
  doc/max_flow/pgr_maxFlowMinCost.rst
  doc/max_flow/pgr_maxFlowMinCost_Cost.rst
  doc/max_flow/pgr_pushRelabel.rst
  doc/mincut/pgr_stoerWagner.rst
  doc/ordering/CMakeLists.txt
  doc/ordering/ordering-family.rst
  doc/ordering/pgr_cuthillMckeeOrdering.rst
  doc/planar/pgr_isPlanar.rst
  doc/spanningTree/pgr_kruskal.rst
  doc/spanningTree/pgr_kruskalBFS.rst
  doc/spanningTree/pgr_kruskalDD.rst
  doc/spanningTree/pgr_kruskalDFS.rst
  doc/spanningTree/pgr_prim.rst
  doc/spanningTree/pgr_primBFS.rst
  doc/spanningTree/pgr_primDD.rst
  doc/spanningTree/pgr_primDFS.rst
  doc/src/experimental.rst
  doc/src/via-category.rst
  doc/topologicalSort/pgr_topologicalSort.rst
  doc/transitiveClosure/pgr_transitiveClosure.rst
  doc/traversal/pgr_depthFirstSearch.rst
Labels: Documentation, Administrative

#2373 Release tasks 3
  doc/astar/pgr_aStar.rst
  doc/bdAstar/pgr_bdAstar.rst
  doc/bdDijkstra/pgr_bdDijkstra.rst
  doc/bellman_ford/pgr_bellmanFord.rst
  doc/bellman_ford/pgr_edwardMoore.rst
  doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
  doc/conf.py.in
  doc/dijkstra/pgr_dijkstra.rst
  doc/dijkstra/pgr_dijkstraNear.rst
  doc/trsp/pgr_trsp.rst
  doc/trsp/pgr_trsp_withPoints.rst
  docqueries/src/migration.result
  docqueries/trsp/doc-trsp.result
  docqueries/trsp/trsp_withPoints.result
  sql/trsp/_trsp.sql
  sql/trsp/_trsp_withPoints.sql
  sql/trsp/trsp.sql
  sql/trsp/trsp_withPoints.sql
  src/trsp/new_trsp.c
  src/trsp/trsp_withPoints.c
  tools/testers/types_check.sql
Labels: TRSP, Bug Fix

#2374 Release tasks 4
  doc/circuits/pgr_hawickCircuits.rst
  doc/conf.py.in
  doc/ordering/pgr_cuthillMckeeOrdering.rst
  doc/pickDeliver/pgr_pickDeliver.rst
  doc/pickDeliver/pgr_pickDeliverEuclidean.rst
  doc/src/pgRouting-concepts.rst
  doc/topology/pgr_analyzeGraph.rst
  doc/topology/pgr_analyzeOneWay.rst
  doc/topology/pgr_createTopology.rst
  doc/topology/pgr_createVerticesTable.rst
  doc/topology/pgr_degree.rst
  doc/topology/pgr_extractVertices.rst
  doc/topology/pgr_nodeNetwork.rst
  doc/trsp/pgr_trsp.rst
  doc/trsp/pgr_trspVia.rst
  doc/trsp/pgr_trspVia_withPoints.rst
  doc/trsp/pgr_trsp_withPoints.rst
  doc/trsp/pgr_turnRestrictedPath.rst
  doc/utilities/pgr_findCloseEdges.rst
  doc/version/pgr_full_version.rst
  doc/version/pgr_version.rst
  doc/withPoints/pgr_withPoints.rst
  doc/withPoints/pgr_withPointsCost.rst
  doc/withPoints/pgr_withPointsCostMatrix.rst
  doc/withPoints/pgr_withPointsDD.rst
  doc/withPoints/pgr_withPointsKSP.rst
  doc/withPoints/pgr_withPointsVia.rst
  docqueries/topology/degree.result
  pgtap/topology/degree/types_check.pg
  sql/topology/degree.sql
Labels: Documentation, Administrative

#2376 Release tasks 6
  .github/workflows/update.yml
  doc/topology/pgr_analyzeOneWay.rst
  doc/trsp/pgr_turnRestrictedPath.rst
  doc/version/pgr_version.rst
  doc/withPoints/pgr_withPointsCost.rst
  include/c_common/get_check_data.h
  pgtap/contraction/linear/directed/issue_1647.pg
  pgtap/contraction/linear/undirected/issue_1647.pg
  pgtap/max_flow/maxCardinalityMatch/inner_query.pg
  pgtap/max_flow/maxCardinalityMatch/no_crash_test.pg
  pgtap/withPoints/withPoints/edge_cases/issue_1640.pg
  pgtap/withPoints/withPoints/edge_cases/issue_2254.pg
  sql/common/_checkcolumn.sql
  src/common/get_check_data.c
  tools/testers/innerQuery.sql
Labels: Administrative

#2380 Fix english typos 2
  .github/workflows/boost_version.yml
  .github/workflows/clang.yml
  .github/workflows/update-locale.yml
  .github/workflows/website.yml
  doc/CMakeLists.txt
  doc/allpairs/pgr_floydWarshall.rst
  doc/bellman_ford/pgr_edwardMoore.rst
  doc/breadthFirstSearch/pgr_binaryBreadthFirstSearch.rst
  doc/dagShortestPath/pgr_dagShortestPath.rst
  doc/max_flow/flow-family.rst
  doc/withPoints/pgr_withPointsCost.rst
  doc/withPoints/pgr_withPointsCostMatrix.rst
  locale/en/LC_MESSAGES/pgrouting_doc_strings.po
  locale/pot/pgrouting_doc_strings.pot
  tools/transifex/update_locale.sh
Labels: Translation, CI

#2383 [conf] ingnoring link latest/pgr
  doc/conf.py.in
Labels: Documentation, CI
