Repository pgRouting/pgrouting, pull requests merged in 2022-10, with the labels that each got.

#2385 Translations update from OSGeo Weblate
  locale/es/LC_MESSAGES/pgrouting_doc_strings.po
Labels: Translation

#2391 Bump MarkusJx/install-boost from 2.3.0 to 2.4.0
  .github/workflows/windows.yml
Labels: Administrative

#2392 The current logic to get the version from the version string depends
  CMakeLists.txt
Labels: Administrative, Build
