Repository pgRouting/pgrouting, pull requests merged in 2022-11, with the labels that each got.

#2419 [incubator] doing some incubation tasks
  ci/bessie/regress.sh
  ci/bessie32/regress.sh
  ci/debbie/regress.sh
  ci/winnie/build_pgrouting.sh
  ci/winnie/package_pgrouting.sh
  tools/developer/addNewVersionLink.sh
  tools/developer/commitByDirectory.sh
  tools/developer/pumpup-dev.sh
  tools/developer/pumpup-micro.sh
  tools/developer/run.sh
  tools/developer/taptest.sh
  tools/developer/translate.sh
  tools/mk-signature-file.pl
  tools/publish-doc.sh
  tools/release-scripts/check-release.sh
  tools/release-scripts/compile-release.sh
  tools/release-scripts/get_signatures.sh
  tools/release-scripts/notes2news.pl
  tools/scripts/test_license.sh
  tools/scripts/test_shell.sh
  tools/scripts/test_signatures.sh
  tools/testers/pg_prove_tests.sh
  tools/testers/setup_db.sh
  tools/testers/test_old.sh
  tools/testers/update-tester.sh
  tools/transifex/build_translations.sh
  tools/transifex/create_translations.sh
  tools/transifex/download_translation.sh
  tools/transifex/init_gettext.sh
  tools/transifex/remove_obsolete_entries.sh
  tools/transifex/update_locale.sh
  tools/transifex/update_transifex.sh
Labels: Administrative

#2436 [lint] removing trailing spaces
  include/c_common/get_check_data.h
  src/common/get_check_data.c
Labels: Developers Doc.

#2443 Fix centos build. References #2415 for pgRouting 3.4.2
  CMakeLists.txt
  src/trsp/trsp.c
Labels: Bug Fix

#2444 Fix for centos build #2415 for pgRouting develop 3.5.0
  CMakeLists.txt
  src/trsp/trsp.c
Labels: Bug Fix
