Repository pgRouting/pgrouting, pull requests merged in 2023-03, with the labels that each got.

#2481 Fix mingw64 compile on newer mingw64 closes #2465
  include/cpp_common/interruption.h
  locale/en/LC_MESSAGES/pgrouting_doc_strings.po
  locale/pot/pgrouting_doc_strings.pot
Labels: Bug Fix

#2480 Fix mingw64 compile (develop)
  include/cpp_common/interruption.h
Labels: Bug Fix

#2460 added postgres 15 as dependency
  .github/workflows/ubuntu.yml
Labels: CI

#2482 Pgsql 15 and no 18.04 tests
  .github/workflows/ubuntu.yml
Labels: CI

#2486 [locale] fix error on locale files
  locale/es/LC_MESSAGES/pgrouting_doc_strings.po
  locale/ja/LC_MESSAGES/pgrouting_doc_strings.po
  locale/ko/LC_MESSAGES/pgrouting_doc_strings.po
  locale/pot/pgrouting_doc_strings.pot
Labels: Translation

#2495 Fix clang warnings
  doc/_static/page_history.js
  include/cpp_common/basePath_SSEC.hpp
  include/cpp_common/identifier.h
  include/cpp_common/identifiers.hpp
  include/cpp_common/xy_vertex.h
  include/vrp/order.h
  include/vrp/pd_orders.h
  include/vrp/tw_node.h
  include/vrp/vehicle.h
  include/vrp/vehicle_node.h
  include/vrp/vehicle_pickDeliver.h
Labels: C/C++

#2497 To cpp arrays input
  include/c_common/arrays_input.h
  src/astar/astar.c
  src/bdAstar/bdAstar.c
  src/bdDijkstra/bdDijkstra.c
  src/bellman_ford/bellman_ford.c
  src/bellman_ford/bellman_ford_neg.c
  src/bellman_ford/edwardMoore.c
  src/breadthFirstSearch/binaryBreadthFirstSearch.c
  src/breadthFirstSearch/breadthFirstSearch.c
  src/circuits/hawickCircuits.c
  src/coloring/edgeColoring.c
  src/coloring/sequentialVertexColoring.c
  src/common/CMakeLists.txt
  src/common/get_check_data.c
  src/contraction/contractGraph.c
  src/cpp_common/CMakeLists.txt
  src/cpp_common/arrays_input.cpp
  src/dagShortestPath/dagShortestPath.c
  src/dijkstra/dijkstra.c
  src/dijkstra/dijkstraVia.c
  src/driving_distance/many_to_dist_driving_distance.c
  src/driving_distance/many_to_dist_withPointsDD.c
  src/max_flow/edge_disjoint_paths.c
  src/max_flow/max_flow.c
  src/max_flow/minCostMaxFlow.c
  src/ordering/cuthillMckeeOrdering.c
  src/spanningTree/kruskal.c
  src/spanningTree/prim.c
  src/traversal/depthFirstSearch.c
  src/trsp/new_trsp.c
  src/trsp/trspVia.c
  src/trsp/trspVia_withPoints.c
  src/trsp/trsp_withPoints.c
  src/withPoints/withPoints.c
  src/withPoints/withPointsVia.c
Labels: C/C++

#2503 Revert "To cpp arrays input"
  include/c_common/arrays_input.h
  src/astar/astar.c
  src/bdAstar/bdAstar.c
  src/bdDijkstra/bdDijkstra.c
  src/bellman_ford/bellman_ford.c
  src/bellman_ford/bellman_ford_neg.c
  src/bellman_ford/edwardMoore.c
  src/breadthFirstSearch/binaryBreadthFirstSearch.c
  src/breadthFirstSearch/breadthFirstSearch.c
  src/circuits/hawickCircuits.c
  src/coloring/edgeColoring.c
  src/coloring/sequentialVertexColoring.c
  src/common/CMakeLists.txt
  src/common/arrays_input.c
  src/common/get_check_data.c
  src/contraction/contractGraph.c
  src/cpp_common/CMakeLists.txt
  src/dagShortestPath/dagShortestPath.c
  src/dijkstra/dijkstra.c
  src/dijkstra/dijkstraVia.c
  src/driving_distance/many_to_dist_driving_distance.c
  src/driving_distance/many_to_dist_withPointsDD.c
  src/max_flow/edge_disjoint_paths.c
  src/max_flow/max_flow.c
  src/max_flow/minCostMaxFlow.c
  src/ordering/cuthillMckeeOrdering.c
  src/spanningTree/kruskal.c
  src/spanningTree/prim.c
  src/traversal/depthFirstSearch.c
  src/trsp/new_trsp.c
  src/trsp/trspVia.c
  src/trsp/trspVia_withPoints.c
  src/trsp/trsp_withPoints.c
  src/withPoints/withPoints.c
  src/withPoints/withPointsVia.c
Labels: C/C++
