Repository pgRouting/pgrouting, pull requests merged in 2023-05, with the labels that each got.

#2515 Fix winnie build (#2514) - develop branch
  ci/winnie/build_pgrouting.sh
  ci/winnie/package_pgrouting.sh
  tools/scripts/test_shell.sh
Labels: CI

#2512 [dijkstra] Removing duplicated code
  NEWS
  doc/src/release_notes.rst
  include/drivers/dijkstra/dijkstra_driver.h
  src/dijkstra/dijkstra.c
  src/dijkstra/dijkstra_driver.cpp
Labels: Dijkstra, C/C++

#2519 Not updating locale on main
  .github/workflows/centos.yml
  .github/workflows/update-locale.yml
Labels: CI

#2521 Dijkstra code simplification
  NEWS
  doc/src/release_notes.rst
  docqueries/topology/degree.result
  include/dijkstra/dijkstra.hpp
  include/dijkstra/drivingDist.hpp
  include/dijkstra/pgr_dijkstra.hpp
  include/dijkstra/pgr_dijkstraVia.hpp
  include/visitors/dijkstra_one_goal_visitor.hpp
  include/visitors/dijkstra_visitors.hpp
  include/yen/pgr_ksp.hpp
  src/alpha_shape/pgr_alphaShape.cpp
  src/dijkstra/dijkstra_driver.cpp
  src/driving_distance/drivedist_driver.cpp
  src/driving_distance/withPoints_dd_driver.cpp
  src/lineGraph/lineGraphFull_driver.cpp
  src/lineGraph/lineGraph_driver.cpp
  src/trsp/trsp_driver.cpp
  src/trsp/trsp_withPoints_driver.cpp
  src/tsp/tsp.cpp
  src/version/_version.h
  src/withPoints/withPoints_driver.cpp
Labels: Enhancement, C/C++
