Repository pgRouting/pgrouting, pull requests merged in 2023-09, with the labels that each got.

#2551 Cleaningcode
  docqueries/driving_distance/doc-pgr_drivingDistance.result
  docqueries/driving_distance/doc-pgr_drivingDistance.test.sql
  docqueries/driving_distance/pgr_drivingDistance.result
  docqueries/driving_distance/pgr_drivingDistance.test.sql
  src/driving_distance/CMakeLists.txt
  src/driving_distance/driving_distance.c
  src/driving_distance/many_to_dist_driving_distance.c
Labels: drivingDistance, Administrative, GSoC

#2554 Bump actions/checkout from 3 to 4
  .github/workflows/boost_version.yml
  .github/workflows/centos.yml
  .github/workflows/check-files.yml
  .github/workflows/check-queries.yml
  .github/workflows/clang.yml
  .github/workflows/doc-check.yml
  .github/workflows/macos.yml
  .github/workflows/release.yml
  .github/workflows/ubuntu.yml
  .github/workflows/update-locale.yml
  .github/workflows/update.yml
  .github/workflows/website.yml
Labels: CI

#2566 Fix #2565 Returning empty results when vertex does not exist
  NEWS
  doc/src/release_notes.rst
  include/dominator/pgr_lengauerTarjanDominatorTree_driver.hpp
  pgtap/dominator/lengauerTarjanDominatorTree/edge_cases.pg
Labels: Bug Fix

#2568 Update centos.yml
  .github/workflows/centos.yml
Labels: CI

#2569 Update centos.yml
  .github/workflows/centos.yml
Labels: CI
